dist: xenial
language: python
python: 3.7

# commands to install dependencies
install: 	
    - pip3 install pipenv
    - pipenv install --dev

# commands to run tests
script:
    - make lint
    - make test
    - make check
